LETTER_BUTTON_WIDTH = 60
LETTER_BUTTON_HEIGHT = 60
ICON_BUTTON_WIDTH = 60
ICON_BUTTON_HEIGHT = 60

FIRST_ROW_OFFSET = 110
SECOND_ROW_OFFSET = 180
THIRD_ROW_OFFSET = 250
FOURTH_ROW_OFFSET = 320
FIFTH_ROW_OFFSET = 390
SIXTH_ROW_OFFSET = 460

FIRST_COL_OFFSET = 110
SECOND_COL_OFFSET = 180
THIRD_COL_OFFSET = 250
FOURTH_COL_OFFSET = 320
FIFTH_COL_OFFSET = 390
SIXTH_COL_OFFSET = 460
SEVENTH_COL_OFFSET = 530
EIGHTH_COL_OFFSET = 600
NINTH_COL_OFFSET = 670
TENTH_COL_OFFSET = 740
ELEVENTH_COL_OFFSET = 810

ICON_BUTTON_ROW_OFFSET = 300

N_NUMBER_MULTIPLE_PHOTOS = 4

KEYBOARD_LAYOUT = [
    # NUMBERS
    ('1', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIRST_COL_OFFSET, FIRST_ROW_OFFSET),
    ('2', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SECOND_COL_OFFSET, FIRST_ROW_OFFSET),
    ('3', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, THIRD_COL_OFFSET, FIRST_ROW_OFFSET),
    ('4', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FOURTH_COL_OFFSET, FIRST_ROW_OFFSET),
    ('5', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIFTH_COL_OFFSET, FIRST_ROW_OFFSET),
    ('6', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SIXTH_COL_OFFSET, FIRST_ROW_OFFSET),
    ('7', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SEVENTH_COL_OFFSET, FIRST_ROW_OFFSET),
    ('8', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, EIGHTH_COL_OFFSET, FIRST_ROW_OFFSET),
    ('9', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, NINTH_COL_OFFSET, FIRST_ROW_OFFSET),
    ('0', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, TENTH_COL_OFFSET, FIRST_ROW_OFFSET),
    # FIRST ROW
    ('q', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIRST_COL_OFFSET, SECOND_ROW_OFFSET),
    ('w', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SECOND_COL_OFFSET, SECOND_ROW_OFFSET),
    ('e', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, THIRD_COL_OFFSET, SECOND_ROW_OFFSET),
    ('r', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FOURTH_COL_OFFSET, SECOND_ROW_OFFSET),
    ('t', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIFTH_COL_OFFSET, SECOND_ROW_OFFSET),
    ('y', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SIXTH_COL_OFFSET, SECOND_ROW_OFFSET),
    ('u', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SEVENTH_COL_OFFSET, SECOND_ROW_OFFSET),
    ('i', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, EIGHTH_COL_OFFSET, SECOND_ROW_OFFSET),
    ('o', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, NINTH_COL_OFFSET, SECOND_ROW_OFFSET),
    ('p', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, TENTH_COL_OFFSET, SECOND_ROW_OFFSET),
    # SECOND ROW
    ('a', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIRST_COL_OFFSET, THIRD_ROW_OFFSET),
    ('s', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SECOND_COL_OFFSET, THIRD_ROW_OFFSET),
    ('d', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, THIRD_COL_OFFSET, THIRD_ROW_OFFSET),
    ('f', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FOURTH_COL_OFFSET, THIRD_ROW_OFFSET),
    ('g', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIFTH_COL_OFFSET, THIRD_ROW_OFFSET),
    ('h', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SIXTH_COL_OFFSET, THIRD_ROW_OFFSET),
    ('j', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SEVENTH_COL_OFFSET, THIRD_ROW_OFFSET),
    ('k', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, EIGHTH_COL_OFFSET, THIRD_ROW_OFFSET),
    ('l', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, NINTH_COL_OFFSET, THIRD_ROW_OFFSET),
    # THIRD ROW
    ('z', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIRST_COL_OFFSET, FOURTH_ROW_OFFSET),
    ('x', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SECOND_COL_OFFSET, FOURTH_ROW_OFFSET),
    ('c', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, THIRD_COL_OFFSET, FOURTH_ROW_OFFSET),
    ('v', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FOURTH_COL_OFFSET, FOURTH_ROW_OFFSET),
    ('b', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIFTH_COL_OFFSET, FOURTH_ROW_OFFSET),
    ('n', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SIXTH_COL_OFFSET, FOURTH_ROW_OFFSET),
    ('m', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SEVENTH_COL_OFFSET, FOURTH_ROW_OFFSET),
    # FOURTH ROW
    ('.', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FIRST_COL_OFFSET, FIFTH_ROW_OFFSET),
    ('-', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, SECOND_COL_OFFSET, FIFTH_ROW_OFFSET),
    ('_', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, THIRD_COL_OFFSET, FIFTH_ROW_OFFSET),
    ('@', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, FOURTH_COL_OFFSET, FIFTH_ROW_OFFSET),
    # FIFTH ROW
    ('@gmail.com', None, None, 110, SIXTH_ROW_OFFSET),
    ('@yahoo.com', None, None, 215, SIXTH_ROW_OFFSET),
    ('@hotmail.com', None, None, 320, SIXTH_ROW_OFFSET),
    ('.com', None, None, 435, SIXTH_ROW_OFFSET),
]
