LETTER_BUTTON_WIDTH = 30
LETTER_BUTTON_HEIGHT = 30
ICON_BUTTON_WIDTH = 60
ICON_BUTTON_HEIGHT = 60

FIRST_LINE_OFFSET = 100
SECOND_LINE_OFFSET = 140
THIRD_LINE_OFFSET = 180
FOURTH_LINE_OFFSET = 220
FIFTH_LINE_OFFSET = 260
ICON_BUTTON_LINE_OFFSET = 300

N_NUMBER_MULTIPLE_PHOTOS = 4

KEYBOARD_LAYOUT = [
    # NUMBERS
    ('1', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 10, FIRST_LINE_OFFSET),
    ('2', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 45, FIRST_LINE_OFFSET),
    ('3', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 80, FIRST_LINE_OFFSET),
    ('4', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 115, FIRST_LINE_OFFSET),
    ('5', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 150, FIRST_LINE_OFFSET),
    ('6', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 185, FIRST_LINE_OFFSET),
    ('7', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 220, FIRST_LINE_OFFSET),
    ('8', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 255, FIRST_LINE_OFFSET),
    ('9', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 290, FIRST_LINE_OFFSET),
    ('0', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 325, FIRST_LINE_OFFSET),
    # FIRST LINE
    ('q', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 10, SECOND_LINE_OFFSET),
    ('w', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 45, SECOND_LINE_OFFSET),
    ('e', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 80, SECOND_LINE_OFFSET),
    ('r', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 115, SECOND_LINE_OFFSET),
    ('t', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 150, SECOND_LINE_OFFSET),
    ('y', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 185, SECOND_LINE_OFFSET),
    ('u', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 220, SECOND_LINE_OFFSET),
    ('i', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 255, SECOND_LINE_OFFSET),
    ('o', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 290, SECOND_LINE_OFFSET),
    ('p', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 325, SECOND_LINE_OFFSET),
    # SECOND LINE
    ('a', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 10, THIRD_LINE_OFFSET),
    ('s', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 45, THIRD_LINE_OFFSET),
    ('d', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 80, THIRD_LINE_OFFSET),
    ('f', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 115, THIRD_LINE_OFFSET),
    ('g', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 150, THIRD_LINE_OFFSET),
    ('h', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 185, THIRD_LINE_OFFSET),
    ('j', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 220, THIRD_LINE_OFFSET),
    ('k', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 255, THIRD_LINE_OFFSET),
    ('l', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 290, THIRD_LINE_OFFSET),
    # THIRD LINE
    ('z', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 10, FOURTH_LINE_OFFSET),
    ('x', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 45, FOURTH_LINE_OFFSET),
    ('c', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 80, FOURTH_LINE_OFFSET),
    ('v', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 115, FOURTH_LINE_OFFSET),
    ('b', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 150, FOURTH_LINE_OFFSET),
    ('n', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 185, FOURTH_LINE_OFFSET),
    ('m', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 220, FOURTH_LINE_OFFSET),
    ('.', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 290, FOURTH_LINE_OFFSET),
    ('@', LETTER_BUTTON_WIDTH, LETTER_BUTTON_HEIGHT, 325, FOURTH_LINE_OFFSET),
    # FOURTH LINE
    ('@gmail.com', None, None, 10, FIFTH_LINE_OFFSET),
    ('@yahoo.com', None, None, 115, FIFTH_LINE_OFFSET),
    ('@hotmail.com', None, None, 220, FIFTH_LINE_OFFSET),
]
