settings:
  EMAIL_SUBJECT: 'Photobooth file'
  EMAIL_BODY: 'A file taken with the photobooth app is attached'
  SENDER_EMAIL: 'your_email@gmail.com'
  SENDER_PASSWORD: 'your_password'
  EVENT_DATE: 'Jan 1 1970'
  EVENT_NAME: 'Event name'
  EVENT_PLACE: 'Event place'
  EVENT_WEBSITE: 'Event website'
  PDF_MESSAGE: 'Message to be included in the generated pdf'
  PDF_SIGNATURE: 'With love! X and Y'
  PDF_TOP_IMG: 'top.png'
  PDF_BOTTOM_IMG: 'bottom.png'
  PDF_MAIN_IMG: 'main.png'
